TuristickaAgencija/TuristickaAgencija/Controllers/PutovanjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TuristickaAgencija.EF;
using TuristickaAgencija.EntityModels;
using TuristickaAgencija.Helper;
using TuristickaAgencija.ViewModel;

namespace TuristickaAgencija.Controllers
{
    public class PutovanjaController : Controller
    {
        private MojContext _db;
        public PutovanjaController(MojContext db)
        {
            _db = db;
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: true)]

        public IActionResult Index()
        {
            List<PutovanjaPrikaziVM> model = _db.Putovanja.Select(x => new PutovanjaPrikaziVM
            {
                PutovanjaId = x.PutovanjaId,
                NazivPutovanja=x.NazivPutovanja,
                OpisPutovanja=x.OpisPutovanja,
                CijenaPutovanja=x.CijenaPutovanja,
                DatumPolaska=x.DatumPolaska.ToString("dd.MM.yyyy"),
                DatumDolaska =x.DatumDolaska.ToString("dd.MM.yyyy"),
                BrojPutnika=x.BrojPutnika,
                PopisPutnika=x.PopisPutnika,

                //Klijent = x.Klijent.Ime+"/ "+x.Klijent.Prezime+"/ "+x.Klijent.JMBG,
                Prevoz=x.Prevoz.Firma.Naziv,
                Smjestaj=x.Smjestaj.NazivSmjestaja
            }).ToList();
            return View(model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Dodaj()
        {
            PutovanjaDodajUrediVM model = new PutovanjaDodajUrediVM
            {
                //Klijent = _db.Klijent.Select(x => new SelectListItem
                //{
                //    Value = x.Id.ToString(),
                //    Text = x.Ime + "/ " + x.Prezime + "/ " + x.JMBG
                //}).ToList(),
                Prevoz = _db.Prevoz.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Firma.Naziv
                }).ToList(),
                Smjestaj = _db.Smjestaj.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NazivSmjestaja
                }).ToList()
            };

            return View(model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Snimi(PutovanjaDodajUrediVM input)
        {
            
                if (!ModelState.IsValid)
                {
                    input.Prevoz = _db.Firma.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Naziv
                    }).ToList();
                    input.Smjestaj = _db.Smjestaj.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.NazivSmjestaja
                    }).ToList();

                    
                return View("Dodaj", input);
                }
             

            
            Putovanja putovanja;
            if (input.PutovanjaId != 0)
            {
                putovanja = _db.Putovanja.Find(input.PutovanjaId);

            }
            else
            {
                putovanja = new Putovanja();
                _db.Putovanja.Add(putovanja);
            }



            putovanja.NazivPutovanja = input.NazivPutovanja;
            putovanja.OpisPutovanja = input.OpisPutovanja;
            putovanja.CijenaPutovanja = input.CijenaPutovanja;
            putovanja.DatumPolaska = input.DatumPolaska;
            putovanja.DatumDolaska = input.DatumDolaska;
            putovanja.BrojPutnika = input.BrojPutnika;
            putovanja.PopisPutnika = input.PopisPutnika;

            //putovanja.KlijentId = input.KlijentId;
            putovanja.PrevozId = input.PrevozId;
            putovanja.SmjestajId = input.SmjestajId;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Obrisi(int id)
        {
            var putovanja = _db.Putovanja.Find(id);
            _db.Putovanja.Remove(putovanja);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Uredi(int id)
        {
            var putovanja = _db.Putovanja.Find(id);

            if (putovanja == null)
            {

                return RedirectToAction(nameof(Index));
            }
            PutovanjaDodajUrediVM model = new PutovanjaDodajUrediVM
            {
                PutovanjaId = id,
                NazivPutovanja = putovanja.NazivPutovanja,
                OpisPutovanja = putovanja.NazivPutovanja,
                CijenaPutovanja = putovanja.CijenaPutovanja,
                DatumPolaska = putovanja.DatumPolaska,
                DatumDolaska = putovanja.DatumDolaska,
                BrojPutnika = putovanja.BrojPutnika,
                PopisPutnika = putovanja.PopisPutnika,

                //KlijentId = putovanja.KlijentId,
                //Klijent = _db.Klijent.Select(x => new SelectListItem
                //{
                //    Value = x.Id.ToString(),
                //    Text = x.Ime + "/ " + x.Prezime + "/ " + x.JMBG
                //}).ToList(),
                PrevozId = putovanja.PrevozId,
                Prevoz = _db.Prevoz.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Firma.Naziv
                }).ToList(),
                SmjestajId = putovanja.SmjestajId,
                Smjestaj = _db.Smjestaj.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NazivSmjestaja
                }).ToList()

            };


            return View("Dodaj", model);
        }
    }
}

TuristickaAgencija/TuristickaAgencija/Views/Putovanja/Dodaj.cshtml
@using TuristickaAgencija.EntityModels;
@model TuristickaAgencija.ViewModel.PutovanjaDodajUrediVM
@{
    if (Model.PutovanjaId == 0)
    {
        ViewData["Title"] = "Dodavanje putovanja";
    }
    else
    {
        ViewData["Title"] = "Uređivanje putovanja";
    }
}



<h3>@ViewData["Title"]</h3>
<hr />
<form asp-controller="Putovanja" asp-action="Snimi">
    <input asp-for="PutovanjaId" type="hidden" />
    <div class="form-group">
        <label asp-for="NazivPutovanja">Naziv putovanja</label>
        <input asp-for="NazivPutovanja" type="text" class="form-control" />
        <span asp-validation-for="NazivPutovanja" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="OpisPutovanja">Opis putovanja</label>
        <input asp-for="OpisPutovanja" type="text" class="form-control" />
        <span asp-validation-for="OpisPutovanja" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CijenaPutovanja">Cijena putovanja</label>
        <input asp-for="CijenaPutovanja" type="text" class="form-control" />
        <span asp-validation-for="CijenaPutovanja" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DatumPolaska">Datum polaska</label>
        <input asp-for="DatumPolaska" type="date" class="form-control" />
        <span asp-validation-for="DatumPolaska" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DatumDolaska">Datum dolaska</label>
        <input asp-for="DatumDolaska" type="date" class="form-control" />
        <span asp-validation-for="DatumDolaska" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BrojPutnika">Broj putnika</label>
        <input asp-for="BrojPutnika" type="number" class="form-control" />
        <span asp-validation-for="BrojPutnika" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PopisPutnika">Popis putnika</label>
        <input asp-for="PopisPutnika" type="text" class="form-control" />
        <span asp-validation-for="PopisPutnika" class="text-danger"></span>
    </div>
    @*<div class="form-group">
        <label asp-for="KlijentId">Klijent </label>
        <select asp-for="KlijentId" class="form-control" asp-items="@Model.Klijent"></select>
    </div>*@
<div class="form-group">
    <label asp-for="PrevozId">Prevoz </label>
    <select asp-for="PrevozId" class="form-control" asp-items="@Model.Prevoz"></select>
    <span asp-validation-for="PrevozId" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="SmjestajId">Smjestaj </label>
    <select asp-for="SmjestajId" class="form-control" asp-items="@Model.Smjestaj"></select>
    <span asp-validation-for="SmjestajId" class="text-danger"></span>
</div>
    <button type="submit" class="btn btn-primary">Spremi</button>
</form>

TuristickaAgencija/TuristickaAgencija/Views/Putovanja/Index.cshtml
@using TuristickaAgencija.ViewModel
@model List<PutovanjaPrikaziVM>


@{

}

<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-left">
                <a asp-controller="Home" asp-action="Index" class="btn btn-info btn-sm">Menu</a>
            </th>
        </tr>
    </thead>
</table>
@if (!Model.Any())
{
    <div class="alert alert-info clearfix">
        <span>Nema putovanja za prikaz.</span>

        <a asp-controller="Putovanja" asp-action="Dodaj" class="btn btn-info btn-xs float-right">Dodaj</a>
    </div>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Naziv putovanja</th>
                <th>Opis putovanja</th>
                <th>Cijena putovanja</th>
                <th>Datum polaska</th>
                <th>Datum dolaska</th>
                <th>Broj putnika</th>
                <th>Popis putnika</th>
                @*<th>Klijent</th>*@
                <th>Prevoz</th>
                <td>Smjestaj</td>
                <th class="text-right">
                    <a asp-controller="Putovanja" asp-action="Dodaj" class="btn btn-info btn-sm">Dodaj</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
            <tr>
                <td>@x.NazivPutovanja</td>
                <td>@x.OpisPutovanja</td>
                <td>@x.CijenaPutovanja</td>
                <td>@x.DatumPolaska</td>
                <td>@x.DatumDolaska</td>
                <td>@x.BrojPutnika</td>
                <td>@x.PopisPutnika</td>

                @*<td>@x.Klijent</td>*@
                <td>@x.Prevoz</td>
                <td>@x.Smjestaj</td>

                <td class="text-right">
                    <a asp-controller="Putovanja" asp-action="Uredi" asp-route-id="@x.PutovanjaId" class="btn btn-info btn-sm">Uredi</a>
                    <a asp-controller="Putovanja" asp-action="Obrisi" asp-route-id="@x.PutovanjaId" class="btn btn-danger btn-sm">Obriši</a>
                </td>
            </tr>
            }

        </tbody>

    </table>


}