TuristickaAgencija/TuristickaAgencija/Controllers/KorisnickiProfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TuristickaAgencija.EF;
using TuristickaAgencija.ViewModel;
using TuristickaAgencija.Helper;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TuristickaAgencija.Controllers
{
    public class KorisnickiProfilController : Controller
    {
        private MojContext _db;
        public KorisnickiProfilController(MojContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Prikazi()
        {
            KorisnickiProfilIndexVM model = new KorisnickiProfilIndexVM();
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var zaposlenik = _db.Zaposlenici.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);


            if (zaposlenik!=null)
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == zaposlenik.KorisnikID);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.KorisnickoIme = zaposlenik.KorisnickiNalog.KorisnickoIme;
                model.Password = zaposlenik.KorisnickiNalog.Lozinka;
               

            }
            else
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.KorisnickoIme = putnik.KorisnickiNalog.KorisnickoIme;
                model.Password = putnik.KorisnickiNalog.Lozinka;
               
                
            }





            return View("Prikazi", model);
        }
        public IActionResult Uredi(int id)
        {
            KorisnickiProfilUrediVM model = new KorisnickiProfilUrediVM();
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var zaposlenik = _db.Zaposlenici.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.PutnikKorisnikId == logiranikorisnik.KorisnickiNalogId);


            if (zaposlenik!=null)
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == zaposlenik.KorisnikID);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.KorisnickoIme = zaposlenik.KorisnickiNalog.KorisnickoIme;
                model.Password = zaposlenik.KorisnickiNalog.Lozinka;
               


            }
            else
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.KorisnickoIme = putnik.KorisnickiNalog.KorisnickoIme;
                model.Password = putnik.KorisnickiNalog.Lozinka;
                //model.Grad = _db.Gradovi.Select(o => new SelectListItem(o.NazivGrada, o.Id.ToString())).ToList();

            }
            return View("Uredi", model);
        }
        public IActionResult KlijentPrikazi()
        {
            KorisnickiProfilIndexVM model = new KorisnickiProfilIndexVM();
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);
            
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.KorisnickoIme = putnik.KorisnickiNalog.KorisnickoIme;
                model.Password = putnik.KorisnickiNalog.Lozinka;



            return View("KlijentPrikazi", model);
        }
        public IActionResult KlijentUredi()
        {
            KorisnickiProfilUrediVM model = new KorisnickiProfilUrediVM();
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.PutnikKorisnikId == logiranikorisnik.KorisnickiNalogId);


            if (putnik != null)
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);
                model.Ime = korisnik.Ime;
                model.Prezime = korisnik.Prezime;
                model.JMBG = korisnik.JMBG;
                model.Kontakt = korisnik.Kontakt;
                model.DatumRodjenja = korisnik.DatumRodjenja;
                model.GradId = (int)korisnik.GradID;
                model.Gradovi = _db.Gradovi.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NazivGrada
                }).ToList();
                model.KorisnickoIme = putnik.KorisnickiNalog.KorisnickoIme;
                model.Password = putnik.KorisnickiNalog.Lozinka;
              
            }
           
            return View("KlijentUredi", model);
        }
        public IActionResult KlijentSnimi(KorisnickiProfilUrediVM model)
        {
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);

           
                if(!ModelState.IsValid)
                {
                model.Gradovi = _db.Gradovi.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.NazivGrada
                }).ToList();
                return View("KlijentUredi",model);
                }
                else
                {
                    var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);

                    korisnik.Kontakt = model.Kontakt;
                    korisnik.Ime = model.Ime;
                    korisnik.Prezime = model.Prezime;
                    korisnik.JMBG = model.JMBG;
                    korisnik.DatumRodjenja = model.DatumRodjenja;
                    korisnik.GradID = model.GradId;
                    putnik.KorisnickiNalog.KorisnickoIme = model.KorisnickoIme;
                    putnik.KorisnickiNalog.Lozinka = model.Password;
                 }
          

            _db.SaveChanges();
            return Redirect("/KlijentHome/Index");
        }
        public IActionResult Snimi(KorisnickiProfilUrediVM model)
        {
            var logiranikorisnik = HttpContext.GetLogiraniKorisnik();
            var zaposlenik = _db.Zaposlenici.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);
            var putnik = _db.PutnikKorisnik.FirstOrDefault(s => s.KorisnickiNalogId == logiranikorisnik.KorisnickiNalogId);

            if (zaposlenik!=null)
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == zaposlenik.KorisnikID);

                korisnik.Kontakt = model.Kontakt;
                zaposlenik.KorisnickiNalog.KorisnickoIme = model.KorisnickoIme;
                zaposlenik.KorisnickiNalog.Lozinka = model.Password;

            }
            else
            {
                var korisnik = _db.Klijent.FirstOrDefault(x => x.Id == putnik.KorisnikId);

                korisnik.Kontakt = model.Kontakt;
                zaposlenik.KorisnickiNalog.KorisnickoIme = model.KorisnickoIme;
                zaposlenik.KorisnickiNalog.Lozinka = model.Password;

            }

            _db.SaveChanges();
            return Redirect("Prikazi");
        }
    }
}

TuristickaAgencija/TuristickaAgencija/Views/KorisnickiProfil/KlijentPrikazi.cshtml
@model TuristickaAgencija.ViewModel.KorisnickiProfilIndexVM

@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Prikazi";
}



<h2>@Model.Ime @Model.Prezime</h2>

<br />



<form action="/KorisnickiProfil/KlijentUredi" method="post">
    <input type="hidden" value="@Model.ProfilId" />

    <h4>O osobi:</h4>

    <div class="form-group">
        <label>Ime: @Model.Ime</label>


    </div>

    <div class="form-group">
        <label>Prezime: @Model.Prezime</label>


    </div>

    <div class="form-group">
        <label>Datum rođenja: @Model.DatumRodjenja.ToShortDateString()</label>

    </div>

    <div class="form-group">
        <label>JMBG: @Model.JMBG</label>


    </div>
    @*<div class="form-group">
        <label>Grad: @Model.Grad</label>


    </div>*@

    <h4>Pristupni podaci:</h4>

    <div class="form-group">
        <label>Korisničko ime: @Model.KorisnickoIme</label>


    </div>


    <h4>Kontakt podaci:</h4>

    <div class="form-group">
        <label>Mobitel/Email: @Model.Kontakt</label>

    </div>

    <br />

    <input type="submit" value="Uredi" class="btn btn-info" />
</form>

TuristickaAgencija/TuristickaAgencija/Views/KorisnickiProfil/KlijentUredi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model TuristickaAgencija.ViewModel.KorisnickiProfilUrediVM

@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Uredi";
}

<h2>Uredi profil</h2>
<form asp-action="KlijentSnimi" asp-controller="KorisnickiProfil" method="post">
    @Html.HiddenFor(s => s.ProfilId)

    <h4>Lični podaci</h4>
        <div class="form-group">
        <label>Ime:</label>
        @Html.TextBoxFor(s => s.Ime, new { @class = "form-control" })
        <span asp-validation-for="Ime" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Prezime:</label>
            @Html.TextBoxFor(s => s.Prezime, new { @class = "form-control" })
            <span asp-validation-for="Prezime" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>JMBG:</label>
            @Html.TextBoxFor(s => s.JMBG, new { @class = "form-control" })
            <span asp-validation-for="JMBG" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Datum rodjenja:</label>
            @Html.TextBoxFor(s => s.DatumRodjenja, new { @class = "form-control" })
            <span asp-validation-for="DatumRodjenja" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="GradId">Grad:</label>
            <select asp-for="GradId" asp-items="Model.Gradovi" class="form-control"></select>
            <span asp-validation-for="GradId" class="text-danger"></span>
        </div>
        <h4>Pristupni podaci:</h4>

        <div class="form-group">
            <label>Korisničko ime:</label>
            @Html.TextBoxFor(s => s.KorisnickoIme, new { @class = "form-control" })
            <span asp-validation-for="KorisnickoIme" class="text-danger"></span>

        </div>

        <div class="form-group">
            <label>Lozinka:</label>
            <input asp-for="Password" class="form-control" type="password" />
            <span asp-validation-for="Password" class="text-danger"></span>

        </div>

        <h4>Kontakt podaci:</h4>

        <div class="form-group">
            <label>Mobitel/Email:</label>
            @Html.TextBoxFor(s => s.Kontakt, new { @class = "form-control" })
        </div>

        <br />

        <input type="submit" value="Snimi" class="btn btn-info" />
</form>

TuristickaAgencija/TuristickaAgencija/Views/KorisnickiProfil/Prikazi.cshtml
@model TuristickaAgencija.ViewModel.KorisnickiProfilIndexVM

@{
    ViewData["Title"] = "Prikazi";
}



<h2>@Model.Ime @Model.Prezime</h2>

<br />



<form action="/KorisnickiProfil/Uredi" method="post">
    <input type="hidden" value="@Model.ProfilId" />

    <h4>O osobi:</h4>

    <div class="form-group">
        <label>Ime: @Model.Ime</label>


    </div>

    <div class="form-group">
        <label>Prezime: @Model.Prezime</label>


    </div>

    <div class="form-group">
        <label>Datum rođenja: @Model.DatumRodjenja.ToShortDateString()</label>

    </div>

    <div class="form-group">
        <label>JMBG: @Model.JMBG</label>


    </div>
    @*<div class="form-group">
        <label>Grad: @Model.Grad</label>


    </div>*@

    <h4>Pristupni podaci:</h4>

    <div class="form-group">
        <label>Korisničko ime: @Model.KorisnickoIme</label>


    </div>


    <h4>Kontakt podaci:</h4>

    <div class="form-group">
        <label>Mobitel/Email: @Model.Kontakt</label>

    </div>

    <br />

    <input type="submit" value="Uredi" class="btn btn-info" />
</form>

TuristickaAgencija/TuristickaAgencija/Views/KorisnickiProfil/Uredi.cshtml
@model TuristickaAgencija.ViewModel.KorisnickiProfilUrediVM

@{
    ViewData["Title"] = "Uredi";
}



<br />
<br />


<form action="/KorisnickiProfil/Snimi" method="post">
    @Html.HiddenFor(s => s.ProfilId)


    <h4>Pristupni podaci:</h4>


    <div class="form-group">
        <label>Korisničko ime:</label>
        @Html.TextBoxFor(s => s.KorisnickoIme, new { @class = "form-control" })
        <span asp-validation-for="KorisnickoIme" class="text-danger"></span>

    </div>

    <div class="form-group">
        <label>Lozinka:</label>
        <input asp-for="Password" class="form-control" type="password" />
        <span asp-validation-for="Password" class="text-danger"></span>

    </div>

    <h4>Kontakt podaci:</h4>


    <div class="form-group">
        <label>Mobitel/Email:</label>
        @Html.TextBoxFor(s => s.Kontakt, new { @class = "form-control" })
    </div>

    <br />

    @*<h4>Grad: </h4>
    <div class="form-group">
        <label>Grad</label>
        <select asp-for="GradID" asp-items="@Model.Grad" class="form-control"></select>
        <span asp-validation-for="GradID" class="text-danger"></span>

    </div>*@

    <input type="submit" value="Snimi" class="btn btn-info" />
</form>